services:
  gmbot:
    build:
      context: .
    container_name: Rezzysite
    env_file:
      - stack.env
    pull_policy: build
    restart: unless-stopped
    volumes:
      - /opt/docker/Rezzysite:/data
